apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-django-app
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: sample-django-app
  template:
    metadata:
      labels:
        app: sample-django-app
    spec:
      containers:
        - name: sample-django-app
          image: pkshahid/django_sample_app:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
